


[sample]
  name = "20241105_DR4_2Q2C"

[path]
    config = "C:\\QM\\QM_config\\20241105_DR4_2Q2C.json"
    dynamic_config = "C:\\QM\\QM_config\\20241105_DR4_2Q2C_config.pkl"
    specification = "C:\\QM\\QM_config\\20241105_DR4_2Q2C_spec.pkl"
    output_root = "C:\\QM\\Data\\20241105_DR4_2Q2C"

